library(SexSpecificExpression)
library(xtable)
load("~/SexSpecificExpression/data/RRs_impact.rda")
load("~/SexSpecificExpression/data/Ler_impact.rda")
load("~/SexSpecificExpression/data/Kondara_impact.rda")
load("~/SexSpecificExpression/data/Ws_impact.rda")
load("~/SexSpecificExpression/data/Qar_impact.rda")
load("~/SexSpecificExpression/data/all_compiled_data.rda")
load("~/SexSpecificExpression/data/gene_lists_three_sets.rda")
load("~/SexSpecificExpression/data/Cvi_impact.rda")

Cvi_data <- impact_list_rates(all_data = all_compiled_data,impact_list = Cvi_impact,gene_list = gene_lists_three_sets,chr_num = 5 )
Kondara_data <- impact_list_rates(all_data = all__compiled_data,impact_list = Kondara_impact,gene_list = gene_lists_three_sets,chr_num = 5)
Ws_data <- impact_list_rates(all_data = all_compiled_data,impact_list = Ws_impact,gene_list = gene_lists_three_sets,chr_num = 5)
RRs_data <- impact_list_rates(all_data = all_compiled_data,impact_list = RRs_impact,gene_list = gene_lists_three_sets,chr_num = 5)
Qar_data <- impact_list_rates(all_data = all_compiled_data,impact_list = Qar_impact,gene_list = gene_lists_three_sets,chr_num = 5)
Ler_data <- impact_list_rates(all_data = all_compiled_data,impact_list = Ler_impact,gene_list = gene_lists_three_sets,chr_num = 5)

Cvi_table <- xtable(Cvi_data$rate_table, caption = "Cvi Moderate Impact")
colnames(Cvi_table) = c("Gene List","Rate")
Kondara_table <- xtable(Kondara_data$rate_table, caption = "Kondara Moderate Impact")
colnames(Kondara_table) = c("Gene List","Rate")
Qar_table <- xtable(Qar_data$rate_table, caption = "Qar Moderate Impact")
colnames(Qar_table) = c("Gene List", "Rate")
Ler_table <- xtable(Ler_data$rate_table, caption = "Ler Moderate Impact")
colnames(Ler_table) = c("Gene List","Rate")
RRs_table <- xtable(RRs_data$rate_table, caption = "RRs Moderate Impact")
colnames(RRs_table) = c("Gene List","Rate")
Ws_table <- xtable(Ws_data$rate_table, caption = "Ws Moderate Impact")
colnames(Ws_table) = c("Gene List","Rate")

background_rate <- c(Cvi_data$background_rate$average_rate,Kondara_data$background_rate$average_rate, Ler_data$background_rate$average_rate, Qar_data$background_rate$average_rate, RRs_data$background_rate$average_rate, Ws_data$background_rate$average_rate)
names <- c("Cvi", "Kondara","Ler","Qar","RRs","Ws")
background.rate <- cbind(names, background_rate)
background.rate.table <- xtable(background.rate, caption = "Background Rates")

print(Cvi_table, caption.placement = "top", include.rownames = FALSE)
print(Kondara_table, caption.placement = "top", include.rownames = FALSE)
print(Ler_table, caption.placement = "top", include.rownames = FALSE)
print(Qar_table, caption.placement = "top", include.rownames = FALSE)
print(RRs_table, caption.placement = "top", include.rownames = FALSE)
print(Ws_table, caption.placement = "top", include.rownames = FALSE)
print(background.rate.table, caption.placement = "top", include.rownames = FALSE)
